version: '3'

services:
  notifier:
    restart: "unless-stopped"
    build: .
    image: fishing-exam-alert-notifier
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./database.sqlite
        target: /fishing_exam_alert/database.sqlite
      - ./fishing_exam_alert/google_creds:/fishing_exam_alert/google_creds
  email_confirmation:
    restart: "unless-stopped"
    image: fishing-exam-alert-notifier
    build: .
    env_file:
      - .env
    volumes:
      - ./fishing_exam_alert/google_creds:/fishing_exam_alert/google_creds
    command: python -u fishing_exam_alert/confirmation.py
